Repository DymOK93/KTL, pull requests merged in 2021-11, with the labels that each got.

#211 Add ktl::forward to ktl::optional::operator=
  include/optional.hpp
Labels: good first issue

#212 Fix missing template parameters pack expansion
  include/tuple.hpp
Labels: good first issue

#229 Removed invalid 'return' statement
  include/mutex.hpp
Labels: bug

#230 Fixed return type of operator=
  include/mutex.hpp
Labels: bug

#228 Using '{}' instead of 'nullptr'; thread_base::set_priority was marked const
  include/thread.hpp
  src/thread.cpp
Labels: invalid

#226 Fixed store and load operations for integral/floating-point atomics
  include/atomic.hpp
Labels: bug

#231 Fixed unexpected freeing of memory in shared_ptr c-tor
  include/smart_pointer.hpp
Labels: bug

#225 Addded workaround for the MSVC linker bug with LTO enabled
  CMakeLists.txt
  modules/fmt/compile.hpp
  runtime/include/bugcheck.hpp
  runtime/src/CMakeLists.txt
Labels: bug

#233 /INCLUDE linker option has been moved to global CMakeLists
  CMakeLists.txt
  runtime/src/CMakeLists.txt
Labels: bug

#234 Fixes of IRQL manipulation routines for implementing tests
  include/type_traits.hpp
  runtime/include/irql.hpp
  runtime/include/type_info.hpp
  runtime/include/type_traits_impl.hpp
  runtime/src/floating_point.cpp
  runtime/src/irql.cpp
  runtime/src/type_info.cpp
Labels: documentation, enhancement

#241 Introduced range size check
  include/algorithm.hpp
Labels: bug

#240 Fixed destroying of array elements
  runtime/include/object_management.hpp
  runtime/src/object_management.cpp
Labels: bug
