Repository DymOK93/KTL, pull requests merged in 2021-12, with the labels that each got.

#244 Add string view overload for `basic_winnt_string::insert`
  include/string.hpp
Labels: enhancement, good first issue

#246 Fixed string insertion and concatenation
  include/string.hpp
Labels: bug

#248 Fixed char_traits
  runtime/include/char_traits_impl.hpp
Labels: bug, enhancement

#253 Added cookie check to exception handlers.
  runtime/src/exc_engine/x64/frame_handler3.cpp
  runtime/src/exc_engine/x64/frame_handler4.cpp
Labels: enhancement

#259 Fixed __GSHandlerCheckCommon signature and handler_data offset
  runtime/include/exc_engine/frame_handler.hpp
  runtime/src/exc_engine/x64/frame_handler3.cpp
  runtime/src/exc_engine/x64/frame_handler4.cpp
Labels: bug

#260 Added documentation and fixed handler data offset
  runtime/include/exc_engine/frame_handler.hpp
  runtime/include/exc_engine/rva.hpp
  runtime/src/exc_engine/CMakeLists.txt
  runtime/src/exc_engine/gs_failure.cpp
  runtime/src/exc_engine/gs_handler.cpp
  runtime/src/exc_engine/x64/catch.hpp
  runtime/src/exc_engine/x64/frame_handler3.cpp
  runtime/src/exc_engine/x64/frame_handler4.cpp
  runtime/src/exc_engine/x64/throw.hpp
Labels: bug, documentation

#261 Added tests for ktl::basic_runtime
  .gitignore
  CMakeLists.txt
  runtime/include/heap.hpp
  runtime/include/preload_initializer.hpp
  runtime/src/basic_runtime.cpp
  runtime/src/preload_initializer.cpp
  tests/CMakeLists.txt
  tests/cmake/AddTest.cmake
  tests/driver.cpp
  tests/dynamic_init/CMakeLists.txt
  tests/dynamic_init/test.cpp
  tests/dynamic_init/test.hpp
  tests/exception_dispatcher/CMakeLists.txt
  tests/exception_dispatcher/test.cpp
  tests/exception_dispatcher/test.hpp
  tests/floating_point/CMakeLists.txt
  tests/floating_point/test.cpp
  tests/floating_point/test.hpp
  tests/heap/CMakeLists.txt
  tests/heap/test.cpp
  tests/heap/test.hpp
  tests/irql/CMakeLists.txt
  tests/irql/test.cpp
  tests/irql/test.hpp
  tests/placement_new/CMakeLists.txt
  tests/placement_new/test.cpp
  tests/placement_new/test.hpp
  tests/preload_init/CMakeLists.txt
  tests/preload_init/test.cpp
  tests/preload_init/test.hpp
  tests/runner/CMakeLists.txt
  tests/runner/container_traits.hpp
  tests/runner/test_runner.cpp
  tests/runner/test_runner.hpp
Labels: enhancement

#262 Managing the state of the APC in ktl::push_lock for Windows 10
  src/push_lock.cpp
Labels: enhancement

#263 The filesystem mini-filters support library has become part of the basic_runtime library as a separate TU
  runtime/include/CMakeLists.txt
  runtime/src/CMakeLists.txt
  runtime/src/minifilter.cpp
  tests/CMakeLists.txt
Labels: enhancement
